FROM alpine:edge as alpine

RUN apk add -U --no-cache ca-certificates go

FROM scratch

EXPOSE 80
WORKDIR /

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=alpine /usr/lib/go/lib/time/zoneinfo.zip /zoneinfo.zip

ENV ZONEINFO=/zoneinfo.zip

COPY root /

CMD ["/root"]